average allocation
PollenDeFi/pollen-subgraph-v3 pull request #20
Opened 2021-12-03 23:29 UTC by hack3r-0m

average allocation = Asset(x).avgAllocation / no. of portfolios / total no. of. rebalances
(since each rebalance creates new portfolio)

2021-12-06 10:19 UTC, avclarke requested changes

2021-12-06 10:19 UTC, avclarke commented on src/mappings/portfolio.ts
> +        asset.avgAllocation = asset.avgAllocation + weights[i]
We'll need to subtract the existing allocations on rebalance and close as well, it should only reflect the current portfolios across users

2021-12-07 01:12 UTC, hack3r-0m commented on schema.graphql
> +  avgAllocation: Int!
will fix this

2021-12-07 01:17 UTC, hack3r-0m commented on src/mappings/portfolio.ts
> +        asset.avgAllocation = asset.avgAllocation + weights[i]
@avclarke to subtract old allocation while rebalance, we can just pass in one more array of old weights and subtract that. let me know your thoughts and i can fix this.

2021-12-08 07:55 UTC, merged